[package]
name = "tasklet"
version = "0.1.1"
authors = ["Stavros Grigoriou <unix121@protonmail.com>"]
edition = "2021"
license = "MIT"
repositoy = "https://github.com/unix121/tasklet"
readme = "README.md"
description = "A task scheduling library."

[dependencies]
cron = "0.8.0"
chrono = "0.4.19"
time = "0.2.25"
log = "0.4.14"

[dev-dependencies]
simple_logger = "1.11.0"
